### ISSUE TITLE
Hager-Zhang archive link yields 404

### ISSUE THREAD

**Issue by ocramz** [meteficha/nonlinear-optimization#3]
The source for the C library pointed in the Haddocks (http://www.math.ufl.edu/~hager/papers/CG/CG_DESCENT-C-3.0.tar.gz) can't be found anymore .

**Comment by msakai** [comment]
It seems that the package is still available from https://www.math.lsu.edu/~hozhang/SoftArchive/CG_DESCENT-C-3.0.tar.gz .
